# docker-compose.yml - Legacy configuration (use docker-compose.pi-native.yml instead)
# This file is kept for compatibility but pi-native is now the default
services:
  api:
    image: ghcr.io/jordanellis73/eggbot/api:latest
    pull_policy: missing  # Only pull if image doesn't exist locally
    restart: unless-stopped
    volumes:
      - api_data:/app/data
      - /dev/i2c-1:/dev/i2c-1  # I2C device access
      - /dev/gpiomem:/dev/gpiomem  # GPIO memory access
      - /run/dbus:/run/dbus:rw
      - /var/run/dbus:/var/run/dbus:rw
      - /sys/class/bluetooth:/sys/class/bluetooth:rw
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiomem:/dev/gpiomem"
    group_add:
      - "994"  # i2c group GID from host
      - "993"  # gpio group GID from host
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
      - SYS_PTRACE
    environment:
      - SIMULATE=false
      - ENV=production
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  ui:
    image: ghcr.io/jordanellis73/eggbot/ui:latest
    pull_policy: missing  # Only pull if image doesn't exist locally
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://192.168.1.194:8000
    depends_on:
      - api
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  api_data:

networks:
  app-network:
    driver: bridge
