services:
  api:
    image: ghcr.io/jordanellis73/eggbot/api:latest
    pull_policy: missing
    restart: unless-stopped
    volumes:
      - /dev/i2c-1:/dev/i2c-1  # I2C device access
      - /dev/gpiomem:/dev/gpiomem  # GPIO memory access
      - api_data:/app/data
      - /run/dbus:/run/dbus:rw
      - /var/run/dbus:/var/run/dbus:rw
      - /sys/class/bluetooth:/sys/class/bluetooth:ro
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/gpiomem:/dev/gpiomem"
    privileged: true  # Required for GPIO access
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
    environment:
      - PI_NATIVE=true
      - SIMULATE=false
      - PYTHONPATH=/app
      - LOG_LEVEL=INFO
    depends_on:
      - pigpiod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  pigpiod:
    image: debian:bullseye-slim
    container_name: pigpiod
    restart: unless-stopped
    privileged: true
    volumes:
      - /dev:/dev
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y wget unzip gcc make &&
        wget https://github.com/joan2937/pigpio/archive/master.zip &&
        unzip master.zip &&
        cd pigpio-master &&
        make &&
        make install &&
        cd .. &&
        rm -rf pigpio-master master.zip &&
        pigpiod -g
      "
    networks:
      - app-network

  ui:
    image: ghcr.io/jordanellis73/eggbot/ui:latest
    pull_policy: missing
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://192.168.1.194:8000
    depends_on:
      - api

volumes:
  api_data:
    
networks:
  app-network:
    driver: bridge
