# docker-compose.yml (updated for registry images)
services:
  api:
    image: ghcr.io/your-username/your-repo-name/api:latest
    restart: unless-stopped
    volumes:
      - api_data:/app/data
    ports:
      - "8000:8000"
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    group_add:
      - "dialout"
    environment:
      - SERIAL_PORT=/dev/ttyACM0
      - BAUD=115200
      - ENV=production
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  ui:
    image: ghcr.io/your-username/your-repo-name/ui:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - api
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  api_data:
