# docker-compose.yml (updated for registry images)
services:
  api:
    image: ghcr.io/jordanellis73/eggbot/api:latest
    pull_policy: missing  # Only pull if image doesn't exist locally
    restart: unless-stopped
    volumes:
      - api_data:/app/data
      - /run/dbus:/run/dbus:rw
      - /var/run/dbus:/var/run/dbus:rw
      - /sys/class/bluetooth:/sys/class/bluetooth:ro
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    group_add:
      - "dialout"
    # Add bluetooth capabilities and access
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
      - NET_BIND_SERVICE
    environment:
      - SERIAL_PORT=/dev/ttyACM0
      - BAUD=115200
      - ENV=production
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  ui:
    image: ghcr.io/jordanellis73/eggbot/ui:latest
    pull_policy: missing  # Only pull if image doesn't exist locally
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://192.168.1.194:8000
    depends_on:
      - api
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

volumes:
  api_data:

networks:
  app-network:
    driver: bridge
